language: node_js
node_js:
- 0.12.7
branches:
  only:
    - engine
before_install:
- openssl aes-256-cbc -K $encrypted_34673a57129f_key -iv $encrypted_34673a57129f_iv
  -in .travis/travis_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.email "373446951@qq.com"
- git config --global user.name "bob12358"
install:
- npm install hexo-cli -g
- npm install hexo --save
- npm install
script:
- hexo clean
- hexo generate
- hexo deploy
